### ISSUE TITLE
[Suggestion] Annoying fan makes a request

### ISSUE THREAD

**Issue by Nekkok** [Affehund/OhMyGoat#1]
Hi! First of all, great mod :D finally, goats have an actual use in the game. It's all simple and nice, and everything fits so nice. The only thing (here I go) is the fact that with other mods installed, I would love the possibility to enable/disable the milk/cheese feature in the config in a future update. Is not that I don't like the cheese (though I have actual intolerance), but this with the culinaire mod I have two types of cheese at a time. I didn't lie about being annoying, is just a preference of mine so I understand this won't see the light. Thanks for reading! Horns are really cool!

**Comment by Affehund** [comment]
Hi, thank you very much for your nice feedback! A config for disabling or adjusting it to the culinaire mod is already planned. 
Glad you enjoy the mod so much.

**Comment by Nekkok** [comment]
Great to hear! Thank you n_n
